spring:
  application:
    name: web-app
    group: libraries

  profiles:
    # dev, prod, prometheus, influx
    active: dev, prometheus

  config:
    import:
      - optional:classpath:actuator.yaml

